// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: commands/group_operation.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Protocol_Message_Commands_GroupOperation: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".GroupOperation"

  /// 操作 0=创建群 1=邀请 2=退群(踢人) 3=加群申请 4=同意加群 5=忽略 6=被退群
  var operation: Int32 = 0

  /// group id
  var group: Int64 = 0

  var members: [Protocol_Message_Misc_User] = []

  /// 请求附属消息
  var content: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.operation)
      case 2: try decoder.decodeSingularInt64Field(value: &self.group)
      case 3: try decoder.decodeRepeatedMessageField(value: &self.members)
      case 4: try decoder.decodeSingularStringField(value: &self.content)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.operation != 0 {
      try visitor.visitSingularInt32Field(value: self.operation, fieldNumber: 1)
    }
    if self.group != 0 {
      try visitor.visitSingularInt64Field(value: self.group, fieldNumber: 2)
    }
    if !self.members.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.members, fieldNumber: 3)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "protocol.message.commands"

extension Protocol_Message_Commands_GroupOperation: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "operation"),
    2: .same(proto: "group"),
    3: .same(proto: "members"),
    4: .same(proto: "content"),
  ]

  func _protobuf_generated_isEqualTo(other: Protocol_Message_Commands_GroupOperation) -> Bool {
    if self.operation != other.operation {return false}
    if self.group != other.group {return false}
    if self.members != other.members {return false}
    if self.content != other.content {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
