// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: commands/login.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Protocol_Message_Commands_Login: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".Login"

  /// 设备多端登录使用 0-手机 1-电脑
  var device: Int32 = 0

  /// 操作平台 0-android 1-ios 2-web
  var platform: Int32 = 0

  /// 建立连接时服务端发送的token
  var token: String = String()

  /// client session key
  var sessionKey: String = String()

  /// 客户端版本
  var version: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularInt32Field(value: &self.device)
      case 2: try decoder.decodeSingularInt32Field(value: &self.platform)
      case 3: try decoder.decodeSingularStringField(value: &self.token)
      case 4: try decoder.decodeSingularStringField(value: &self.sessionKey)
      case 5: try decoder.decodeSingularStringField(value: &self.version)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.device != 0 {
      try visitor.visitSingularInt32Field(value: self.device, fieldNumber: 1)
    }
    if self.platform != 0 {
      try visitor.visitSingularInt32Field(value: self.platform, fieldNumber: 2)
    }
    if !self.token.isEmpty {
      try visitor.visitSingularStringField(value: self.token, fieldNumber: 3)
    }
    if !self.sessionKey.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionKey, fieldNumber: 4)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "protocol.message.commands"

extension Protocol_Message_Commands_Login: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "device"),
    2: .same(proto: "platform"),
    3: .same(proto: "token"),
    4: .standard(proto: "session_key"),
    5: .same(proto: "version"),
  ]

  func _protobuf_generated_isEqualTo(other: Protocol_Message_Commands_Login) -> Bool {
    if self.device != other.device {return false}
    if self.platform != other.platform {return false}
    if self.token != other.token {return false}
    if self.sessionKey != other.sessionKey {return false}
    if self.version != other.version {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
