// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: types/anchor.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Protocol_Message_Types_Anchor: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".Anchor"

  /// 链接
  var href: String = String()

  /// 需要做超链接文本起始下标
  var start: Int32 = 0

  /// 超链接文本字符(非字节)长度
  var len: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularStringField(value: &self.href)
      case 2: try decoder.decodeSingularInt32Field(value: &self.start)
      case 3: try decoder.decodeSingularInt32Field(value: &self.len)
      default: break
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.href.isEmpty {
      try visitor.visitSingularStringField(value: self.href, fieldNumber: 1)
    }
    if self.start != 0 {
      try visitor.visitSingularInt32Field(value: self.start, fieldNumber: 2)
    }
    if self.len != 0 {
      try visitor.visitSingularInt32Field(value: self.len, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "protocol.message.types"

extension Protocol_Message_Types_Anchor: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "href"),
    2: .same(proto: "start"),
    3: .same(proto: "len"),
  ]

  func _protobuf_generated_isEqualTo(other: Protocol_Message_Types_Anchor) -> Bool {
    if self.href != other.href {return false}
    if self.start != other.start {return false}
    if self.len != other.len {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
